--- 
name: Census income

info: https://archive.ics.uci.edu/ml/datasets/Census+Income

urls:
- https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data
- https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.test
- https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.names

cite: > 
    https://archive.ics.uci.edu/ml/citation_policy.html

    @misc{Lichman:2013 ,
    author = "M. Lichman",
    year = "2013",
    title = "{UCI} Machine Learning Repository",
    url = "http://archive.ics.uci.edu/ml",
    institution = "University of California, Irvine, School of Information and Computer Sciences" } 
