--- 
name: Bank Marketing

info: https://archive.ics.uci.edu/ml/datasets/Bank+Marketing

urls:
- https://archive.ics.uci.edu/ml/machine-learning-databases/00222/bank-additional.zip

cite: > 
    [Moro et al., 2014] S. Moro, P. Cortez and P. Rita. A Data-Driven Approach to Predict the Success of Bank Telemarketing. Decision Support Systems, Elsevier, 62:22-31, June 2014
